### ISSUE TITLE
Local mounted engines can't find Enginefile

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-docker-build#26]
When using a local engine, the output always shows:

+> NO ENGINEFILE FOUND
   We couldn't read the Enginefile for the engine your app is using.
   If you just added a custom engine to your Boxfile, you will need to
   `nanobox reload` to mount it into the build container.
   If this persists, contact us on IRC or submit an issue on github
   at nanobox-io/nanobox/issues.

---

   IRC   : #nanobox (freenode)

---

I manually looked in the build1 container and the Enginefile is there. I suspect the hook is looking in the wrong location?

**Comment by glinton** [comment]
Resolved with #28
