### ISSUE TITLE
Unified standard for user-defined custom configuration

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-docker-build#34]
It is proposed that a unified standard for allowing custom user-defined configuration be established. Partly to take the tedium away from engine developers, and also to ensure a certain user-defined configuration will always be available regardless of the engine.

The following nodes will available in the 'build' section of the Boxfile:
- packages
  
  Nanobox provided pkgsrc packages that will be installed before any of the prepare or build scripts are run. This attribute will be a list of packages.
- prepare
  
  A command or list of commands to be executed prior to running the engine's prepare script. 
- before
  
  A command or list of commands to be executed prior to running the engine's build script.
- after
  
  A command or list of commands to be executed after running the engine's build script.

**Comment by glinton** [comment]
In place (via #36 #49)
